### ISSUE TITLE
[BUG] - Carousel Dots Inconsistent placement

### ISSUE THREAD

**Issue by brendon-ng** [cs130-w21/16#59]
## Description
The placement of the carousel dots varies depending on device and on image size being displayed.

## Steps to Reproduce
Steps to reproduce the bug:
- [ ] Click on Dish Card of various dishes on iPhone
- [ ] Click on same cards on iPhone simulator
- [ ] Relevant examples: (on the same device) Ribeye Dinner vs. Molten Chocolate Cake
- [ ] Relevant examples: (on iPhone vs. Simulator) Ribeye Dinner

## Expected Behavior
Dots should either be consistently visible at the bottom of the image or not present for each image.
Also, if possible could we make the image flush against the top of the white div (e.g. no red between) 
Stylistically, it might look good if the image goes all the way to the top of the screen (e.g. no red on top either) worth exploring.

## Additional Context
Possible solutions: force all images to have the same size, but it might be weird with certain sized images and where the items are placed within those images?

## Relevant screenshots
Ribeye Dinner on simulator:
<img width="420" alt="Screen Shot 2021-02-13 at 11 44 21 PM" src="https://user-images.githubusercontent.com/40370559/107871407-14320f80-6e56-11eb-8a63-012df8ecd451.png">
Ribeye Dinner on iPhone:
![IMG_8B89903F5BED-1](https://user-images.githubusercontent.com/40370559/107871412-1dbb7780-6e56-11eb-8c49-3a10908dd86a.jpeg)
Molten Chocolate Cake on iPhone:
![IMG_1465](https://user-images.githubusercontent.com/40370559/107871420-2613b280-6e56-11eb-8ee2-5fb8309af513.PNG)

**Comment by jcgubbi** [comment]
We aren't using carousel dots, deleting.
